/scout_mini/teleop_twist_joy_node:
  ros__parameters:
    axis_linear:
      x: 1
    scale_linear:
      x: 1.0
    scale_linear_turbo:
      x: 1.5

    axis_angular:
      yaw: 2
    scale_angular:
      yaw: 1.0

    enable_button: 4  # L1 shoulder button
    enable_turbo_button: 5  # R1 shoulder button
    
