/scout_mini/teleop_twist_joy_node:
  ros__parameters:
    axis_linear:
      x: 1
    scale_linear:
      x: 1.0 # speed in m/s
    scale_linear_turbo:
      x: 1.5

    axis_angular:
      yaw: 0 # before was 2
    scale_angular:
      yaw: 1.0 # speed in rad/s

    enable_button: 4  # L1 shoulder button
    enable_turbo_button: 5  # R1 shoulder button
    
    require_enable_button: true 


teleop_twist_joy_node:
  ros__parameters:
    axis_linear:
      x: 2
    scale_linear:
      x: 1.0 # speed in m/s
    scale_linear_turbo:
      x: 1.0

    axis_angular:
      yaw: 1 
    scale_angular:
      yaw: 1.0 # speed in rad/s

    enable_button: 7  # L1 shoulder button
    enable_turbo_button: 5  # R1 shoulder button
    
    require_enable_button: true 